import type { Brand, Category, Product } from "./types";

// Sample data shaped like the real Laravel API (Product/Category/Brand), extended with
// merchandising fields (rating, deliveryEstimate, warranty) pulled from the real Microless
// import feed — see the "Monitors" products below, transcribed directly from a live
// uae.microless.com API response. Everything else follows the same shape/style so the whole
// page reads consistently once real data replaces it.

export const mockBrands: Brand[] = [
  { id: 1, name: "ASUS", slug: "asus", logo: null },
  { id: 2, name: "MSI", slug: "msi", logo: null },
  { id: 3, name: "Dell", slug: "dell", logo: null },
  { id: 4, name: "HP", slug: "hp", logo: null },
  { id: 5, name: "Lenovo", slug: "lenovo", logo: null },
  { id: 6, name: "NVIDIA", slug: "nvidia", logo: null },
  { id: 7, name: "Corsair", slug: "corsair", logo: null },
  { id: 8, name: "Logitech", slug: "logitech", logo: null },
  { id: 9, name: "Samsung", slug: "samsung", logo: null },
  { id: 10, name: "Razer", slug: "razer", logo: null },
];

function brand(slug: string): Brand {
  const found = mockBrands.find((b) => b.slug === slug);
  if (!found) throw new Error(`Unknown mock brand: ${slug}`);
  return found;
}

// Two-level hierarchy (parent_id/children, matching CategoryController's real shape) so the
// nav mega menu has real subcategories to show. Components' children (graphics-cards,
// processors, storage) are "real" — products are tagged to them directly, same as before.
// The other subcategories are presentational nav taxonomy for this phase.
export const mockCategories: Category[] = [
  {
    id: 1,
    name: "Laptops",
    slug: "laptops",
    description: "Gaming, business and everyday laptops",
    image_url: null,
    parent_id: null,
    total_products_count: 142,
    children: [
      { id: 11, name: "Gaming Laptops", slug: "gaming-laptops", description: null, image_url: null, parent_id: 1, total_products_count: 68 },
      { id: 12, name: "Business Laptops", slug: "business-laptops", description: null, image_url: null, parent_id: 1, total_products_count: 41 },
      { id: 13, name: "2-in-1 & Touch", slug: "2-in-1-laptops", description: null, image_url: null, parent_id: 1, total_products_count: 33 },
    ],
  },
  {
    id: 2,
    name: "Desktops",
    slug: "desktops",
    description: "Prebuilt and custom gaming desktops",
    image_url: null,
    parent_id: null,
    total_products_count: 58,
    children: [
      { id: 21, name: "Gaming PCs", slug: "gaming-pcs", description: null, image_url: null, parent_id: 2, total_products_count: 29 },
      { id: 22, name: "Prebuilt Desktops", slug: "prebuilt-desktops", description: null, image_url: null, parent_id: 2, total_products_count: 20 },
      { id: 23, name: "Mini PCs", slug: "mini-pcs", description: null, image_url: null, parent_id: 2, total_products_count: 9 },
    ],
  },
  {
    id: 3,
    name: "Components",
    slug: "components",
    description: "Graphics cards, processors and storage",
    image_url: null,
    parent_id: null,
    total_products_count: 100,
    children: [
      { id: 31, name: "Graphics Cards", slug: "graphics-cards", description: "NVIDIA and AMD GPUs", image_url: null, parent_id: 3, total_products_count: 34 },
      { id: 32, name: "Processors", slug: "processors", description: "Intel and AMD CPUs", image_url: null, parent_id: 3, total_products_count: 27 },
      { id: 33, name: "Storage", slug: "storage", description: "SSDs, HDDs and memory", image_url: null, parent_id: 3, total_products_count: 39 },
    ],
  },
  {
    id: 5,
    name: "Monitors",
    slug: "monitors",
    description: "Gaming and productivity displays",
    image_url: null,
    parent_id: null,
    total_products_count: 46,
    children: [
      { id: 51, name: "Gaming Monitors", slug: "gaming-monitors", description: null, image_url: null, parent_id: 5, total_products_count: 22 },
      { id: 52, name: "4K & Ultrawide", slug: "4k-ultrawide-monitors", description: null, image_url: null, parent_id: 5, total_products_count: 15 },
      { id: 53, name: "Office Monitors", slug: "office-monitors", description: null, image_url: null, parent_id: 5, total_products_count: 9 },
    ],
  },
  {
    id: 7,
    name: "Accessories",
    slug: "accessories",
    description: "Keyboards, mice, headsets and more",
    image_url: null,
    parent_id: null,
    total_products_count: 91,
    children: [
      { id: 71, name: "Keyboards & Mice", slug: "keyboards-mice", description: null, image_url: null, parent_id: 7, total_products_count: 47 },
      { id: 72, name: "Headsets", slug: "headsets", description: null, image_url: null, parent_id: 7, total_products_count: 24 },
      { id: 73, name: "Webcams & Streaming", slug: "webcams-streaming", description: null, image_url: null, parent_id: 7, total_products_count: 20 },
    ],
  },
];

function category(slug: string): Category {
  for (const top of mockCategories) {
    if (top.slug === slug) return top;
    const child = top.children?.find((c) => c.slug === slug);
    if (child) return child;
  }
  throw new Error(`Unknown mock category: ${slug}`);
}

// Curated 12-up list for the homepage "Shop by Category" strip — a flatter mix of
// top-level and popular subcategories than the 5-item nav taxonomy above, since the
// homepage rewards more entry points. Reuses the same underlying category records
// (and real product counts) rather than inventing separate data.
export const homeCategories: Category[] = [
  "laptops",
  "desktops",
  "graphics-cards",
  "processors",
  "monitors",
  "storage",
  "accessories",
  "keyboards-mice",
  "headsets",
  "gaming-laptops",
  "gaming-pcs",
  "webcams-streaming",
].map(category);

const TOMORROW = "Delivery tomorrow";
const ONE_YEAR = "1 Year warranty";

export const mockProducts: Product[] = [
  // ---- Laptops ----
  {
    id: 1,
    name: "ASUS ROG Strix G16 Gaming Laptop",
    slug: "asus-rog-strix-g16",
    description: "16\" QHD 240Hz display built for competitive gaming.",
    category: category("laptops"),
    brand: brand("asus"),
    price: "7499.00",
    sale_price: "6299.00",
    cpu: "Intel Core i9-14900HX",
    gpu: "NVIDIA GeForce RTX 4070",
    ram: "32GB DDR5",
    storage: "1TB NVMe SSD",
    specs: { Display: "16\" QHD 240Hz" },
    primary_image_url: null,
    images_gallery_urls: [],
    featured: true,
    status: "active",
    badge: "Best Seller",
    badge_color: "emerald",
    variants: [],
    rating: { average: 4.7, count: 38 },
    deliveryEstimate: TOMORROW,
    warranty: ONE_YEAR,
  },
  {
    id: 2,
    name: "MSI Katana 15 Gaming Laptop",
    slug: "msi-katana-15",
    description: "15.6\" FHD 144Hz, everyday gaming performance.",
    category: category("laptops"),
    brand: brand("msi"),
    price: "4299.00",
    sale_price: null,
    cpu: "Intel Core i7-13620H",
    gpu: "NVIDIA GeForce RTX 4060",
    ram: "16GB DDR5",
    storage: "512GB NVMe SSD",
    specs: { Display: "15.6\" FHD 144Hz" },
    primary_image_url: null,
    images_gallery_urls: [],
    featured: true,
    status: "active",
    badge: "New",
    badge_color: "blue",
    variants: [],
    rating: null,
    deliveryEstimate: TOMORROW,
    warranty: ONE_YEAR,
  },
  {
    id: 3,
    name: "Dell XPS 14 Business Laptop",
    slug: "dell-xps-14",
    description: "Ultra-portable OLED display for professionals.",
    category: category("laptops"),
    brand: brand("dell"),
    price: "8999.00",
    sale_price: null,
    cpu: "Intel Core Ultra 7 155H",
    gpu: "Intel Arc Graphics",
    ram: "32GB LPDDR5",
    storage: "1TB NVMe SSD",
    specs: { Display: "14.5\" 3.2K OLED" },
    primary_image_url: null,
    images_gallery_urls: [],
    featured: false,
    status: "active",
    badge: null,
    badge_color: null,
    variants: [],
    rating: { average: 4.5, count: 12 },
    deliveryEstimate: "Delivery in 2 days",
    warranty: ONE_YEAR,
  },
  {
    id: 4,
    name: "Lenovo Legion Pro 7i",
    slug: "lenovo-legion-pro-7i",
    description: "Flagship gaming laptop with liquid metal cooling.",
    category: category("laptops"),
    brand: brand("lenovo"),
    price: "11999.00",
    sale_price: "10499.00",
    cpu: "Intel Core i9-14900HX",
    gpu: "NVIDIA GeForce RTX 4090",
    ram: "32GB DDR5",
    storage: "2TB NVMe SSD",
    specs: { Display: "16\" WQXGA 240Hz" },
    primary_image_url: null,
    images_gallery_urls: [],
    featured: true,
    status: "active",
    badge: "-12%",
    badge_color: "red",
    variants: [],
    rating: { average: 4.9, count: 21 },
    deliveryEstimate: TOMORROW,
    warranty: "2 Year warranty",
  },
  {
    id: 16,
    name: "HP Victus 16 Gaming Laptop",
    slug: "hp-victus-16",
    description: "Everyday gaming laptop with great value.",
    category: category("laptops"),
    brand: brand("hp"),
    price: "3499.00",
    sale_price: null,
    cpu: "AMD Ryzen 5 7640HS",
    gpu: "NVIDIA GeForce RTX 4050",
    ram: "16GB DDR5",
    storage: "512GB NVMe SSD",
    specs: { Display: "16.1\" FHD 144Hz" },
    primary_image_url: null,
    images_gallery_urls: [],
    featured: false,
    status: "active",
    badge: null,
    badge_color: null,
    variants: [],
    rating: { average: 4.3, count: 64 },
    deliveryEstimate: TOMORROW,
    warranty: ONE_YEAR,
  },

  // ---- Desktops ----
  {
    id: 5,
    name: "HP Omen 25L Gaming Desktop",
    slug: "hp-omen-25l",
    description: "Compact tower with tool-free chassis access.",
    category: category("desktops"),
    brand: brand("hp"),
    price: "6499.00",
    sale_price: null,
    cpu: "AMD Ryzen 7 7700X",
    gpu: "NVIDIA GeForce RTX 4070 Ti",
    ram: "32GB DDR5",
    storage: "1TB NVMe SSD",
    specs: {},
    primary_image_url: null,
    images_gallery_urls: [],
    featured: true,
    status: "active",
    badge: null,
    badge_color: null,
    variants: [],
    rating: { average: 4.6, count: 9 },
    deliveryEstimate: "Delivery in 2 days",
    warranty: ONE_YEAR,
  },
  {
    id: 6,
    name: "ASUS ROG Strix G16CH Desktop",
    slug: "asus-rog-strix-g16ch",
    description: "Built for 4K gaming and streaming.",
    category: category("desktops"),
    brand: brand("asus"),
    price: "9299.00",
    sale_price: "8199.00",
    cpu: "Intel Core i7-14700F",
    gpu: "NVIDIA GeForce RTX 4080 Super",
    ram: "32GB DDR5",
    storage: "2TB NVMe SSD",
    specs: {},
    primary_image_url: null,
    images_gallery_urls: [],
    featured: false,
    status: "active",
    badge: "-12%",
    badge_color: "red",
    variants: [],
    rating: null,
    deliveryEstimate: TOMORROW,
    warranty: ONE_YEAR,
  },

  // ---- Graphics Cards ----
  {
    id: 7,
    name: "NVIDIA GeForce RTX 4080 Super",
    slug: "nvidia-rtx-4080-super",
    description: "16GB GDDR6X, DLSS 3.5 ray tracing.",
    category: category("graphics-cards"),
    brand: brand("nvidia"),
    price: "4199.00",
    sale_price: null,
    cpu: null,
    gpu: "16GB GDDR6X",
    ram: null,
    storage: null,
    specs: {},
    primary_image_url: null,
    images_gallery_urls: [],
    featured: true,
    status: "active",
    badge: "New",
    badge_color: "blue",
    variants: [],
    rating: { average: 4.8, count: 15 },
    deliveryEstimate: TOMORROW,
    warranty: ONE_YEAR,
  },
  {
    id: 8,
    name: "NVIDIA GeForce RTX 4070 Ti",
    slug: "nvidia-rtx-4070-ti",
    description: "12GB GDDR6X, exceptional 1440p performance.",
    category: category("graphics-cards"),
    brand: brand("nvidia"),
    price: "2899.00",
    sale_price: "2599.00",
    cpu: null,
    gpu: "12GB GDDR6X",
    ram: null,
    storage: null,
    specs: {},
    primary_image_url: null,
    images_gallery_urls: [],
    featured: false,
    status: "active",
    badge: "-10%",
    badge_color: "red",
    variants: [],
    rating: { average: 4.6, count: 27 },
    deliveryEstimate: TOMORROW,
    warranty: ONE_YEAR,
  },

  // ---- Processors ----
  {
    id: 9,
    name: "Intel Core i9-14900K",
    slug: "intel-core-i9-14900k",
    description: "24 cores, up to 6.0GHz turbo boost.",
    category: category("processors"),
    brand: brand("msi"),
    price: "2199.00",
    sale_price: null,
    cpu: "24-core, up to 6.0GHz",
    gpu: null,
    ram: null,
    storage: null,
    specs: {},
    primary_image_url: null,
    images_gallery_urls: [],
    featured: false,
    status: "active",
    badge: null,
    badge_color: null,
    variants: [],
    rating: { average: 4.7, count: 33 },
    deliveryEstimate: TOMORROW,
    warranty: ONE_YEAR,
  },

  // ---- Storage ----
  {
    id: 12,
    name: "Corsair MP600 Pro 2TB NVMe SSD",
    slug: "corsair-mp600-pro-2tb",
    description: "PCIe Gen4, up to 7,100MB/s read speeds.",
    category: category("storage"),
    brand: brand("corsair"),
    price: "899.00",
    sale_price: "749.00",
    cpu: null,
    gpu: null,
    ram: null,
    storage: "2TB NVMe Gen4",
    specs: {},
    primary_image_url: null,
    images_gallery_urls: [],
    featured: false,
    status: "active",
    badge: "-17%",
    badge_color: "red",
    variants: [],
    rating: { average: 4.9, count: 51 },
    deliveryEstimate: TOMORROW,
    warranty: "5 Year warranty",
  },
  {
    id: 13,
    name: "Corsair Vengeance 32GB DDR5",
    slug: "corsair-vengeance-32gb-ddr5",
    description: "6000MHz kit, RGB, XMP 3.0 ready.",
    category: category("storage"),
    brand: brand("corsair"),
    price: "649.00",
    sale_price: null,
    cpu: null,
    gpu: null,
    ram: "32GB DDR5-6000",
    storage: null,
    specs: {},
    primary_image_url: null,
    images_gallery_urls: [],
    featured: false,
    status: "active",
    badge: null,
    badge_color: null,
    variants: [],
    rating: { average: 4.8, count: 19 },
    deliveryEstimate: TOMORROW,
    warranty: "Lifetime warranty",
  },

  // ---- Accessories ----
  {
    id: 14,
    name: "Logitech G Pro X Superlight 2",
    slug: "logitech-g-pro-x-superlight-2",
    description: "60g wireless gaming mouse, HERO 2 sensor.",
    category: category("accessories"),
    brand: brand("logitech"),
    price: "549.00",
    sale_price: null,
    cpu: null,
    gpu: null,
    ram: null,
    storage: null,
    specs: {},
    primary_image_url: null,
    images_gallery_urls: [],
    featured: true,
    status: "active",
    badge: "New",
    badge_color: "blue",
    variants: [],
    rating: { average: 4.7, count: 44 },
    deliveryEstimate: TOMORROW,
    warranty: "2 Year warranty",
  },
  {
    id: 15,
    name: "Razer BlackWidow V4 Pro",
    slug: "razer-blackwidow-v4-pro",
    description: "Mechanical gaming keyboard with command dial.",
    category: category("accessories"),
    brand: brand("razer"),
    price: "799.00",
    sale_price: "679.00",
    cpu: null,
    gpu: null,
    ram: null,
    storage: null,
    specs: {},
    primary_image_url: null,
    images_gallery_urls: [],
    featured: false,
    status: "active",
    badge: "-15%",
    badge_color: "red",
    variants: [],
    rating: { average: 4.4, count: 8 },
    deliveryEstimate: TOMORROW,
    warranty: "2 Year warranty",
  },

  // ---- Monitors — transcribed from a live uae.microless.com "Monitors" category response ----
  {
    id: 101,
    name: "Dell U2725QE UltraSharp 27\" Thunderbolt Hub Monitor",
    slug: "dell-u2725qe-ultrasharp-27",
    description: "27\" IPS 4K UHD, 120Hz, 140W USB-C PD hub monitor.",
    category: category("monitors"),
    brand: brand("dell"),
    price: "4480.61",
    sale_price: "2585.00",
    cpu: null,
    gpu: null,
    ram: null,
    storage: null,
    specs: {
      "Screen Size": "27\"",
      Resolution: "3840 x 2160",
      "Panel Type": "IPS",
      "Response Time": "5 ms",
    },
    primary_image_url: null,
    images_gallery_urls: [],
    featured: true,
    status: "active",
    badge: "Best Seller",
    badge_color: "emerald",
    variants: [],
    rating: null,
    deliveryEstimate: "Delivery tomorrow, Aug 31",
    warranty: ONE_YEAR,
  },
  {
    id: 102,
    name: "ASUS ROG Strix XG34WCDMS Gaming Monitor",
    slug: "asus-rog-strix-xg34wcdms",
    description: "34\" QD-OLED ultrawide, 280Hz, G-SYNC Compatible.",
    category: category("monitors"),
    brand: brand("asus"),
    price: "3635.00",
    sale_price: "3432.99",
    cpu: null,
    gpu: null,
    ram: null,
    storage: null,
    specs: {
      "Screen Size": "34\"",
      Resolution: "3440 x 1440",
      "Panel Type": "QD-OLED",
      "Response Time": "0.03 ms",
    },
    primary_image_url: null,
    images_gallery_urls: [],
    featured: true,
    status: "active",
    badge: null,
    badge_color: null,
    variants: [],
    rating: null,
    deliveryEstimate: "Delivery tomorrow, Aug 31",
    warranty: ONE_YEAR,
  },
  {
    id: 103,
    name: "ASUS TUF Gaming VG279QM5A Monitor",
    slug: "asus-tuf-gaming-vg279qm5a",
    description: "27\" Fast IPS FHD, 240Hz, FreeSync & G-Sync compatible.",
    category: category("monitors"),
    brand: brand("asus"),
    price: "823.66",
    sale_price: "697.10",
    cpu: null,
    gpu: null,
    ram: null,
    storage: null,
    specs: {
      "Screen Size": "27\"",
      Resolution: "1920 x 1080",
      "Panel Type": "Fast IPS",
      "Response Time": "0.3 ms",
    },
    primary_image_url: null,
    images_gallery_urls: [],
    featured: false,
    status: "active",
    badge: "-15%",
    badge_color: "red",
    variants: [],
    rating: { average: 5.0, count: 2 },
    deliveryEstimate: "Delivery tomorrow, Aug 31",
    warranty: ONE_YEAR,
  },
  {
    id: 104,
    name: "Dell UltraSharp 32 U3225QE Thunderbolt Hub Monitor",
    slug: "dell-ultrasharp-32-u3225qe",
    description: "32\" IPS 4K UHD, 120Hz, adjustable stand.",
    category: category("monitors"),
    brand: brand("dell"),
    price: "4590.90",
    sale_price: "3269.00",
    cpu: null,
    gpu: null,
    ram: null,
    storage: null,
    specs: {
      "Screen Size": "32\"",
      Resolution: "3840 x 2160",
      "Panel Type": "IPS",
      "Response Time": "5 ms",
    },
    primary_image_url: null,
    images_gallery_urls: [],
    featured: true,
    status: "active",
    badge: "Back to School",
    badge_color: "blue",
    variants: [],
    rating: null,
    deliveryEstimate: "Delivery tomorrow, Aug 31",
    warranty: ONE_YEAR,
  },
  {
    id: 105,
    name: "Dell 27\" P2725H FHD IPS Monitor",
    slug: "dell-27-p2725h",
    description: "27\" FHD IPS, 100Hz, 99% sRGB color gamut.",
    category: category("monitors"),
    brand: brand("dell"),
    price: "742.35",
    sale_price: "630.00",
    cpu: null,
    gpu: null,
    ram: null,
    storage: null,
    specs: {
      "Screen Size": "27\"",
      Resolution: "1920 x 1080",
      "Panel Type": "IPS",
      "Response Time": "5 ms",
    },
    primary_image_url: null,
    images_gallery_urls: [],
    featured: false,
    status: "active",
    badge: "-15%",
    badge_color: "red",
    variants: [],
    rating: { average: 5.0, count: 2 },
    deliveryEstimate: "Delivery tomorrow, Aug 31",
    warranty: ONE_YEAR,
  },
  {
    id: 106,
    name: "Dell 24\" P2425H FHD IPS Monitor",
    slug: "dell-24-p2425h",
    description: "24\" FHD IPS, 100Hz, flicker-free.",
    category: category("monitors"),
    brand: brand("dell"),
    price: "668.12",
    sale_price: "499.00",
    cpu: null,
    gpu: null,
    ram: null,
    storage: null,
    specs: {
      "Screen Size": "24\"",
      Resolution: "1920 x 1080",
      "Panel Type": "IPS",
      "Response Time": "5 ms",
    },
    primary_image_url: null,
    images_gallery_urls: [],
    featured: false,
    status: "active",
    badge: "Back to School",
    badge_color: "blue",
    variants: [],
    rating: { average: 5.0, count: 2 },
    deliveryEstimate: "Delivery tomorrow, Aug 31",
    warranty: ONE_YEAR,
  },
  {
    id: 107,
    name: "ASUS ROG Strix XG27UQDMS Gaming Monitor",
    slug: "asus-rog-strix-xg27uqdms",
    description: "27\" QD-OLED 4K UHD, 240Hz, G-SYNC.",
    category: category("monitors"),
    brand: brand("asus"),
    price: "4038.99",
    sale_price: "3496.50",
    cpu: null,
    gpu: null,
    ram: null,
    storage: null,
    specs: {
      "Screen Size": "27\"",
      Resolution: "3840 x 2160",
      "Panel Type": "QD-OLED",
      "Response Time": "0.03 ms",
    },
    primary_image_url: null,
    images_gallery_urls: [],
    featured: false,
    status: "active",
    badge: "-13%",
    badge_color: "red",
    variants: [],
    rating: null,
    deliveryEstimate: "Delivery tomorrow, Aug 31",
    warranty: ONE_YEAR,
  },
  {
    id: 108,
    name: "ASUS TUF Gaming VG259QM5A Monitor",
    slug: "asus-tuf-gaming-vg259qm5a",
    description: "25\" Fast IPS FHD, 240Hz, FreeSync & G-Sync compatible.",
    category: category("monitors"),
    brand: brand("asus"),
    price: "669.00",
    sale_price: "599.00",
    cpu: null,
    gpu: null,
    ram: null,
    storage: null,
    specs: {
      "Screen Size": "25\"",
      Resolution: "1920 x 1080",
      "Panel Type": "Fast IPS",
      "Response Time": "0.3 ms",
    },
    primary_image_url: null,
    images_gallery_urls: [],
    featured: false,
    status: "active",
    badge: "Back to School",
    badge_color: "blue",
    variants: [],
    rating: null,
    deliveryEstimate: "Delivery tomorrow, Aug 31",
    warranty: ONE_YEAR,
  },
];

export function productsByCategory(slug: string): Product[] {
  return mockProducts.filter((p) => p.category.slug === slug);
}

export const featuredProducts = mockProducts.filter((p) => p.featured);
export const dealProducts = mockProducts.filter((p) => p.sale_price !== null);
export const newArrivals = mockProducts.filter((p) => p.badge === "New");
